version: "3.8"

services:
  n8n:
    image: n8nio/n8n
    container_name: n8n
    restart: always
    ports:
      - "5678:5678"
    environment:
      - DB_POSTGRESDB_HOST=postgres
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_DATABASE=agent_memory
      - DB_POSTGRESDB_USER=aiuser
      - DB_POSTGRESDB_PASSWORD=supersecurepassword
    volumes:
      - n8n_data:/home/node/.n8n
    depends_on:
      - postgres

  postgres:
    image: postgres:15
    container_name: ai_postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: aiuser
      POSTGRES_PASSWORD: supersecurepassword
      POSTGRES_DB: agent_memory
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  n8n_data:
  pgdata:

